### ISSUE TITLE
Different results (false positives) when running action

### ISSUE THREAD

**Issue by michaelmior** [rkusa/eslint-action#1]
I tried this on a repository of mine and it seems to be mostly working. However, I noticed some warnings being generated that I do not see when locally and they are in fact in correct.

Here's an [example](https://github.com/michaelmior/relational-playground/commit/3cd89df654e13968fb8c44c906101c6f2deb2055#annotation_55927728) of a an unused variable warning. You can see the variable is used a couple lines later. I do not see this warning when running eslint locally on my project. Any idea why this could be happening?

**Comment by rkusa** [comment]
Sorry for the late response, I accidentally disabled notifications for this repo. Since this action does not work with the release version of Github actions anymore, I am going to archive it. I guess the recommended alternative are [Problem Matchers](https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers) now. Here is an example problem matcher for eslint: https://github.com/actions/setup-node/blob/master/.github/eslint-compact.json
