### ISSUE TITLE
Not working for pull_request events?

### ISSUE THREAD

**Issue by nomego** [rkusa/eslint-action#2]
On https://github.com/Neovici/cosmoz-treenode/pull/17/checks?check_run_id=209177055 I got:
```
2019/09/01 15:10:48 no handler for the received event type "pull_request"
```

**Comment by rkusa** [comment]
Sorry for the late response, I accidentally disabled notifications for this repo. Since this action does not work with the release version of Github actions anymore, I am going to archive it. I guess the recommended alternative are [Problem Matchers](https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers) now. Here is an example problem matcher for eslint: https://github.com/actions/setup-node/blob/master/.github/eslint-compact.json
